OrdererOrgs:
  - Name: Orderer
    Domain: acornpub.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Sales1
    Domain: sales1.acornpub.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Customer
    Domain: customer.acornpub.com
    Template:
      Count: 2
    Users:
      Count: 1
